// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
const envUrl = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_URL = envUrl || (projectId ? `https://${projectId}.supabase.co` : '');
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error('Supabase env ausente. Configure VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no .env.');
}
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});
